### ISSUE TITLE
Remove reference to window inside of the IFFE

### ISSUE THREAD

**Issue by jakobo** [ericdrowell/concrete#10]
https://github.com/ericdrowell/concrete/blob/427ae6ccd6cdffdbf6c6ebc36a70cb98ecccc8c5/src/concrete.js#L4

Currently, we check pixel ration in an IFFE. However, it doesn't protect against the window var in SSR situations. Attempting to import concrete **anywhere in the dependency tree** will result in the error:

```
ReferenceError: window is not defined
    at Object../node_modules/concretejs/build/concrete.min.js
      (/usr/src/node_modules/elgrapho/engine/dist/ElGrapho.min.js:28:53354)
```

Fix is similar to a UMD harness:

```js
Concrete.PIXEL_RATIO = (function (win) {
  return (win && win.devicePixelRatio) || 1;
})(typeof window !== 'undefined' ? window : null);
```

**Comment by thecodedrift** [comment]
_closed, as the issue is likely stale / not applicable at this point_
