### ISSUE TITLE
Adding Hit to DOM

### ISSUE THREAD

**Issue by nhrones** [ericdrowell/concrete#3]
It seemed to me that adding the Hit canvas to the DOM is not actually required. 

Concrete.Layer line 180
    this.container.appendChild(this.hit.canvas);

If the  above line is commented out, the three circles example works as expected.
By not adding this to the DOM it would seem that DOM performance may be improved, even thought the style is set to display = 'none'.

If this is not the case, please explain.

**Comment by ericdrowell** [comment]
this was done on purpose - the advantage of adding the hit canvas to the dom is that it makes it really easy to debug hit regions by just changing display to 'block'.  adding a few dom elements to the document won't really impact performance.  It's not like hundreds of them are being added.  

Ultimately, the debugging convenience outweighs the minuscule perf/ memory impact.  I'll definitely keep an eye on this thought - if for some situations it did become a problem, I could just add a debugging API to make the hit regions visible.

**Comment by nhrones** [comment]
Thanks for the quick response. I love the simplicity of this library. I've converted a copy to Typescript/ES6 just for kicks.

**Comment by ericdrowell** [comment]
no problem, and thanks!

**Comment by nhrones** [comment]
Eric,
Do you think that by using pixelRatio in Scene for width/scale, but not
using it in Hit may create issues in IOS?
