### ISSUE TITLE
Why Concrete.Scene.setSize() sets this.id ?

### ISSUE THREAD

**Issue by matthieudanet** [ericdrowell/concrete#7]
Why `Concrete.Scene.setSize()` sets his `id` property while `id` is already defined in `Concrete.Scene` constructor ?

https://github.com/ericdrowell/concrete/blob/35f870ed2d3b57ebc753e2cf010ee35b5040bdfb/src/concrete.js#L327

Is this an oversight?

**Comment by ericdrowell** [comment]
yes this is an oversight.  Thank you!
